"""Enots--Wolley on a thinned prime coordinate system.

For stride ``k``, retain the prime coordinates

    p_1, p_{1+k}, p_{1+2k}, ...

and forbid every other prime factor entirely. Thus ``k=3`` retains
``2, 7, 17, 29, ...`` and no generated noninitial term is divisible by 3 or 5.

The production generator works directly in the multiplicative monoid generated
by the retained primes. It never enumerates multipliers containing forbidden
prime coordinates.
"""

from __future__ import annotations

from bisect import bisect_left
from dataclasses import dataclass, field
from functools import partial
from heapq import heappop, heappush
from math import gcd, prod

from ..core import SequenceDefinition
from ..object_space import PositiveIntegers
from ..projections import prime_exponent_projection, primes_through
from .enots_wolley import is_candidate, prime_support
from .every_kth_prime_enots_wolley import prime_index


def _validate_k(k: int) -> None:
    if type(k) is not int:
        raise TypeError("k must be an integer")
    if k < 1:
        raise ValueError("k must be positive")


def is_retained_prime(value: int, k: int) -> bool:
    """Return whether ``value`` is one of p_1, p_{1+k}, p_{1+2k}, ... ."""

    _validate_k(k)
    index = prime_index(value)
    return index is not None and (index - 1) % k == 0


@dataclass(frozen=True, slots=True)
class EveryKthPrimeOnlyPolicy:
    """Allow exactly integers whose prime support uses retained coordinates."""

    k: int

    def __post_init__(self) -> None:
        _validate_k(self.k)

    def allows(self, value: int) -> bool:
        if value < 2:
            return False
        support = prime_support(value)
        return bool(support) and all(is_retained_prime(prime, self.k) for prime in support)


@dataclass
class ReferenceEveryKthPrimeOnlyEnotsWolleyGenerator:
    """Slow direct scanner used as a correctness oracle for arbitrary k."""

    k: int = 2
    policy: EveryKthPrimeOnlyPolicy = field(init=False)
    terms: list[int] = field(init=False)
    used: set[int] = field(init=False)

    def __post_init__(self) -> None:
        self.policy = EveryKthPrimeOnlyPolicy(self.k)
        self.terms = [1, 2]
        self.used = {1, 2}

    def _next_candidate(self) -> int:
        previous = self.terms[-1]
        two_back = self.terms[-2]
        candidate = 2
        while True:
            if (
                candidate not in self.used
                and self.policy.allows(candidate)
                and is_candidate(candidate, previous, two_back)
            ):
                return candidate
            candidate += 1

    def extend_to(self, count: int) -> None:
        if count < 0:
            raise ValueError("count must be nonnegative")
        if count <= len(self.terms):
            return
        if len(self.terms) < 2:
            raise RuntimeError(
                "ReferenceEveryKthPrimeOnlyEnotsWolleyGenerator state is missing "
                "initial terms"
            )

        while len(self.terms) < count:
            candidate = self._next_candidate()
            self.terms.append(candidate)
            self.used.add(candidate)


@dataclass
class EveryKthPrimeOnlyEnotsWolleyGenerator:
    """EW generator whose candidate streams live directly in the retained monoid.

    Let ``R_k = {p_1, p_{1+k}, p_{1+2k}, ...}`` and let ``M_k`` be the
    multiplicative monoid generated by ``R_k``. Every stream prime is itself in
    ``R_k``, hence

        p*m is an allowed integer  <=>  m is in M_k.

    The generic factor-restricted generator used to scan all ordinary integer
    multipliers and permanently reject those containing forbidden primes. This
    implementation instead maintains the increasing list of ``M_k`` multipliers
    with a segmented sieve. All active prime streams share that one table.

    Per-stream successor maps are therefore needed only for historically used
    products, not for structural policy failures. Local two-back exclusions are
    still tested with ``gcd`` because they depend on the current state.

    Candidate new-prime testing also avoids factorization: for ``candidate=p*m``
    with stream prime ``p`` already in the predecessor support, the candidate
    introduces a new prime exactly when repeatedly dividing ``m`` by predecessor
    primes leaves a remainder greater than 1.
    """

    k: int = 2
    policy: EveryKthPrimeOnlyPolicy = field(init=False)
    terms: list[int] = field(init=False)
    used: set[int] = field(init=False)

    # All positive M_k values through multiplier_limit, in increasing order.
    # The list is shared by every candidate stream in this generator instance.
    multiplier_values: list[int] = field(default_factory=lambda: [1], repr=False)
    multiplier_limit: int = 1

    # For each stream prime, a successor-with-delete structure over indices into
    # multiplier_values. Only globally used products are deleted permanently.
    multiplier_successors: dict[int, dict[int, int]] = field(
        default_factory=dict,
        repr=False,
    )

    def __post_init__(self) -> None:
        self.policy = EveryKthPrimeOnlyPolicy(self.k)
        self.terms = [1, 2]
        self.used = {1, 2}

    def _extend_multiplier_table(self, required_value: int) -> None:
        """Extend the sorted M_k multiplier table through ``required_value``.

        Extension is segmented. A segment starts with every integer provisionally
        allowed, then multiples of forbidden prime coordinates are crossed out.
        Surviving integers have no forbidden prime divisor, hence lie exactly in
        the retained-prime monoid M_k.
        """

        if required_value <= self.multiplier_limit:
            return

        while self.multiplier_limit < required_value:
            lower = self.multiplier_limit + 1
            upper = max(required_value, 64, 2 * self.multiplier_limit)
            flags = bytearray(b"\x01") * (upper - lower + 1)

            for index, prime in enumerate(primes_through(upper), start=1):
                if (index - 1) % self.k == 0:
                    continue
                first = ((lower + prime - 1) // prime) * prime
                if first > upper:
                    continue
                offset = first - lower
                count = (upper - first) // prime + 1
                flags[offset::prime] = b"\x00" * count

            self.multiplier_values.extend(
                lower + offset for offset, allowed in enumerate(flags) if allowed
            )
            self.multiplier_limit = upper

    def _ensure_multiplier_index(self, index: int) -> None:
        if index < 0:
            raise ValueError("multiplier index must be nonnegative")
        while index >= len(self.multiplier_values):
            self._extend_multiplier_table(max(64, 2 * self.multiplier_limit))

    def _index_at_least(self, lower_bound: int) -> int:
        """Return the first M_k multiplier index whose value is >= lower_bound."""

        lower_bound = max(1, lower_bound)
        while self.multiplier_values[-1] < lower_bound:
            self._extend_multiplier_table(max(lower_bound, 2 * self.multiplier_limit))
        return bisect_left(self.multiplier_values, lower_bound)

    def _find_multiplier_successor(self, stream_prime: int, index: int) -> int:
        """Find the first multiplier index not deleted for ``stream_prime``."""

        self._ensure_multiplier_index(index)
        parents = self.multiplier_successors.setdefault(stream_prime, {})
        current = index
        path: list[int] = []
        while current in parents:
            path.append(current)
            current = parents[current]
            self._ensure_multiplier_index(current)
        for item in path:
            parents[item] = current
        return current

    def _delete_multiplier_index(self, stream_prime: int, index: int) -> bool:
        """Permanently delete one used-product multiplier index from a stream."""

        surviving = self._find_multiplier_successor(stream_prime, index)
        if surviving != index:
            return False
        parents = self.multiplier_successors.setdefault(stream_prime, {})
        parents[index] = self._find_multiplier_successor(stream_prime, index + 1)
        return True

    def _next_unused_multiplier_index(self, stream_prime: int, index: int) -> int:
        """Return the next index whose stream product is globally unused."""

        parents = self.multiplier_successors.setdefault(stream_prime, {})
        index = self._find_multiplier_successor(stream_prime, index)
        while True:
            multiplier = self.multiplier_values[index]
            if stream_prime * multiplier not in self.used:
                return index
            successor = self._find_multiplier_successor(stream_prime, index + 1)
            parents[index] = successor
            index = successor

    def _next_stream_index(
        self,
        stream_prime: int,
        lower_index: int,
        forbidden_radical: int,
    ) -> int:
        """Return the least unused M_k multiplier satisfying local exclusions."""

        index = max(0, lower_index)
        while True:
            index = self._next_unused_multiplier_index(stream_prime, index)
            multiplier = self.multiplier_values[index]
            if gcd(multiplier, forbidden_radical) == 1:
                return index
            index += 1

    @staticmethod
    def _multiplier_introduces_new_prime(
        multiplier: int,
        previous_support: frozenset[int],
    ) -> bool:
        """Test the EW new-prime condition without factoring ``multiplier``."""

        remainder = multiplier
        for prime in previous_support:
            while remainder % prime == 0:
                remainder //= prime
            if remainder == 1:
                return False
        return remainder > 1

    def _retire_used_value(self, value: int) -> int:
        """Eagerly retire already-materialized stream representations of value."""

        deletions = 0
        for stream_prime in prime_support(value):
            multiplier = value // stream_prime
            if multiplier > self.multiplier_limit:
                continue
            index = bisect_left(self.multiplier_values, multiplier)
            if (
                index < len(self.multiplier_values)
                and self.multiplier_values[index] == multiplier
            ):
                deletions += self._delete_multiplier_index(stream_prime, index)
        return deletions

    def _next_candidate(self) -> int:
        previous = self.terms[-1]
        two_back = self.terms[-2]
        previous_support = prime_support(previous)
        two_back_support = prime_support(two_back)
        shared_primes = tuple(sorted(previous_support - two_back_support))
        if not shared_primes:
            raise RuntimeError(
                "prime-coordinate EW state has no predecessor prime disjoint "
                "from the two-back term"
            )

        heap: list[tuple[int, int, int, int]] = []
        earlier_shared_product = 1
        two_back_radical = prod(two_back_support)

        for stream_prime in shared_primes:
            forbidden_radical = two_back_radical * earlier_shared_product
            index = self._next_stream_index(
                stream_prime,
                0,
                forbidden_radical,
            )
            multiplier = self.multiplier_values[index]
            heappush(
                heap,
                (
                    stream_prime * multiplier,
                    stream_prime,
                    index,
                    forbidden_radical,
                ),
            )
            earlier_shared_product *= stream_prime

        while heap:
            candidate, stream_prime, index, forbidden_radical = heappop(heap)
            multiplier = self.multiplier_values[index]

            # Stream construction guarantees: candidate is an unused allowed
            # integer, shares with the predecessor, and is coprime to two-back.
            # Only the predecessor-external prime condition remains.
            if self._multiplier_introduces_new_prime(multiplier, previous_support):
                return candidate

            index = self._next_stream_index(
                stream_prime,
                index + 1,
                forbidden_radical,
            )
            multiplier = self.multiplier_values[index]
            heappush(
                heap,
                (
                    stream_prime * multiplier,
                    stream_prime,
                    index,
                    forbidden_radical,
                ),
            )

        raise RuntimeError("prime-coordinate EW candidate heap unexpectedly exhausted")

    def extend_to(self, count: int) -> None:
        if count < 0:
            raise ValueError("count must be nonnegative")
        if count <= len(self.terms):
            return
        if len(self.terms) < 2:
            raise RuntimeError(
                "EveryKthPrimeOnlyEnotsWolleyGenerator state is missing initial terms"
            )

        while len(self.terms) < count:
            candidate = self._next_candidate()
            self.terms.append(candidate)
            self.used.add(candidate)
            self._retire_used_value(candidate)


def make_every_kth_prime_only_enots_wolley_definition(
    *,
    id: str,
    k: int,
    name: str,
    aliases: tuple[str, ...] = (),
) -> SequenceDefinition[int]:
    """Build one registered member of the every-kth-prime-only EW family."""

    _validate_k(k)
    return SequenceDefinition[int](
        id=id,
        oeis=None,
        name=name,
        aliases=aliases,
        generator_factory=partial(EveryKthPrimeOnlyEnotsWolleyGenerator, k=k),
        generator_version=2,
        definition_version=1,
        offset=1,
        object_space=PositiveIntegers(),
        projections={"prime-exponents": prime_exponent_projection()},
        description=(
            "Lexicographically earliest sequence starting 1, 2 and obeying the "
            "Enots--Wolley rule after deleting all prime coordinates except "
            f"p_1, p_{{1+{k}}}, p_{{1+2*{k}}}, ... . Every prime factor of every "
            "later term must lie in that retained prime subsequence."
        ),
    )


EVERY_SECOND_PRIME_ONLY_ENOTS_WOLLEY = make_every_kth_prime_only_enots_wolley_definition(
    id="X000009",
    k=2,
    name="Every-second-prime-only Enots--Wolley",
    aliases=(
        "every-second-prime-only-ew",
        "prime-coordinate-ew-2",
        "prime-stride-ew-2",
    ),
)

EVERY_THIRD_PRIME_ONLY_ENOTS_WOLLEY = make_every_kth_prime_only_enots_wolley_definition(
    id="X000010",
    k=3,
    name="Every-third-prime-only Enots--Wolley",
    aliases=(
        "every-third-prime-only-ew",
        "prime-coordinate-ew-3",
        "prime-stride-ew-3",
    ),
)

EVERY_FOURTH_PRIME_ONLY_ENOTS_WOLLEY = make_every_kth_prime_only_enots_wolley_definition(
    id="X000011",
    k=4,
    name="Every-fourth-prime-only Enots--Wolley",
    aliases=(
        "every-fourth-prime-only-ew",
        "prime-coordinate-ew-4",
        "prime-stride-ew-4",
    ),
)

EVERY_KTH_PRIME_ONLY_ENOTS_WOLLEY_DEFINITIONS = (
    EVERY_SECOND_PRIME_ONLY_ENOTS_WOLLEY,
    EVERY_THIRD_PRIME_ONLY_ENOTS_WOLLEY,
    EVERY_FOURTH_PRIME_ONLY_ENOTS_WOLLEY,
)
