"""Enots--Wolley on sparse prime-index coordinate systems.

The allowed prime coordinates are selected by their one-based prime index.
Three registered families are provided:

- square indices: ``p_1, p_4, p_9, p_16, ...``;
- powers of two: ``p_1, p_2, p_4, p_8, ...``;
- self powers: ``p_1, p_4, p_27, p_256, ...``.

This is intentionally a straightforward first implementation.  The candidate
logic follows the existing prime-coordinate-only generator, while the retained
multiplicative monoid is enumerated directly by merging the sorted streams
``p * M`` for retained primes ``p``.  That avoids scanning enormous forbidden
integer intervals in the very sparse families.
"""

from __future__ import annotations

from bisect import bisect_left
from dataclasses import dataclass, field
from functools import partial
from heapq import heappop, heappush
from math import gcd, isqrt, prod
from typing import Literal

from ..core import SequenceDefinition
from ..object_space import PositiveIntegers
from ..projections import prime_exponent_projection
from .enots_wolley import is_candidate, prime_support
from .every_kth_prime_enots_wolley import nth_prime, prime_index

PrimeIndexFamily = Literal["square", "power_of_two", "self_power"]

_VALID_FAMILIES: frozenset[str] = frozenset(
    {"square", "power_of_two", "self_power"}
)


def _validate_family(family: str) -> None:
    if family not in _VALID_FAMILIES:
        allowed = ", ".join(sorted(_VALID_FAMILIES))
        raise ValueError(f"unknown prime-index family {family!r}; expected one of {allowed}")


def is_retained_prime_index(index: int, family: PrimeIndexFamily) -> bool:
    """Return whether one-based prime index ``index`` belongs to ``family``."""

    _validate_family(family)
    if type(index) is not int:
        raise TypeError("prime index must be an integer")
    if index < 1:
        return False

    if family == "square":
        root = isqrt(index)
        return root * root == index

    if family == "power_of_two":
        return index & (index - 1) == 0

    # self_power: 1^1, 2^2, 3^3, ...
    base = 1
    while True:
        value = base**base
        if value >= index:
            return value == index
        base += 1


def is_retained_prime(value: int, family: PrimeIndexFamily) -> bool:
    """Return whether prime ``value`` is retained by the selected index family."""

    index = prime_index(value)
    return index is not None and is_retained_prime_index(index, family)


@dataclass(frozen=True, slots=True)
class SparsePrimeIndexOnlyPolicy:
    """Allow exactly integers supported on one sparse prime-index family."""

    family: PrimeIndexFamily

    def __post_init__(self) -> None:
        _validate_family(self.family)

    def allows(self, value: int) -> bool:
        if value < 2:
            return False
        support = prime_support(value)
        return bool(support) and all(
            is_retained_prime(prime, self.family) for prime in support
        )


@dataclass
class ReferenceSparsePrimeIndexOnlyEnotsWolleyGenerator:
    """Very slow direct integer scanner used only as a tiny correctness oracle."""

    family: PrimeIndexFamily = "square"
    policy: SparsePrimeIndexOnlyPolicy = field(init=False)
    terms: list[int] = field(init=False)
    used: set[int] = field(init=False)

    def __post_init__(self) -> None:
        _validate_family(self.family)
        self.policy = SparsePrimeIndexOnlyPolicy(self.family)
        self.terms = [1, 2]
        self.used = {1, 2}

    def _next_candidate(self) -> int:
        previous = self.terms[-1]
        two_back = self.terms[-2]
        candidate = 2
        while True:
            if (
                candidate not in self.used
                and self.policy.allows(candidate)
                and is_candidate(candidate, previous, two_back)
            ):
                return candidate
            candidate += 1

    def extend_to(self, count: int) -> None:
        if count < 0:
            raise ValueError("count must be nonnegative")
        if count <= len(self.terms):
            return
        while len(self.terms) < count:
            candidate = self._next_candidate()
            self.terms.append(candidate)
            self.used.add(candidate)


@dataclass
class SparsePrimeIndexOnlyEnotsWolleyGenerator:
    """Simple retained-monoid EW generator for sparse prime-index families.

    ``multiplier_values`` is the increasing multiplicative monoid generated by
    the retained primes.  Instead of sieving ordinary integer intervals, it is
    produced by a k-way heap merge of the streams ``p * multiplier_values``.
    A not-yet-opened retained prime acts as the next stream boundary.
    """

    family: PrimeIndexFamily = "square"
    policy: SparsePrimeIndexOnlyPolicy = field(init=False)
    terms: list[int] = field(init=False)
    used: set[int] = field(init=False)

    multiplier_values: list[int] = field(default_factory=lambda: [1], repr=False)

    # Heap entries are (product, retained_prime, multiplier_index).
    monoid_heap: list[tuple[int, int, int]] = field(default_factory=list, repr=False)
    next_allowed_position: int = 0
    next_unopened_prime: int | None = None

    # Per candidate-stream successor-with-delete tables over multiplier_values.
    multiplier_successors: dict[int, dict[int, int]] = field(
        default_factory=dict,
        repr=False,
    )

    def __post_init__(self) -> None:
        _validate_family(self.family)
        self.policy = SparsePrimeIndexOnlyPolicy(self.family)
        self.terms = [1, 2]
        self.used = {1, 2}

    def _allowed_prime_index(self, position: int) -> int:
        """Return the prime index of the zero-based retained-prime position."""

        if position < 0:
            raise ValueError("retained-prime position must be nonnegative")
        base = position + 1
        if self.family == "square":
            return base * base
        if self.family == "power_of_two":
            return 1 << position
        return base**base

    def _peek_next_unopened_prime(self, upper_bound: int | None = None) -> int | None:
        """Return the next retained prime when it could matter below a bound.

        The elementary bound ``p_n > n`` lets very sparse families postpone an
        expensive ``nth_prime`` call until the open monoid streams have actually
        reached the next retained prime's index.
        """

        if self.next_unopened_prime is not None:
            return self.next_unopened_prime

        index = self._allowed_prime_index(self.next_allowed_position)
        if upper_bound is not None and index > upper_bound:
            return None

        self.next_unopened_prime = nth_prime(index)
        return self.next_unopened_prime

    def _open_next_prime_stream(self) -> None:
        prime = self._peek_next_unopened_prime()
        assert prime is not None
        heappush(self.monoid_heap, (prime, prime, 0))
        self.next_allowed_position += 1
        self.next_unopened_prime = None

    def _append_next_multiplier(self) -> None:
        """Append the next distinct value of the retained multiplicative monoid."""

        while True:
            if not self.monoid_heap:
                self._open_next_prime_stream()
                continue

            open_min = self.monoid_heap[0][0]
            unopened = self._peek_next_unopened_prime(open_min)
            if unopened is not None and unopened <= open_min:
                self._open_next_prime_stream()
                continue

            value = open_min
            entries: list[tuple[int, int, int]] = []
            while self.monoid_heap and self.monoid_heap[0][0] == value:
                entries.append(heappop(self.monoid_heap))

            # Every representation of the same monoid value is consumed at once,
            # so the shared table stays strictly increasing.
            if value != self.multiplier_values[-1]:
                self.multiplier_values.append(value)

            for _, prime, multiplier_index in entries:
                next_index = multiplier_index + 1
                # The value just appended is enough to advance every popped
                # stream by one slot.
                if next_index >= len(self.multiplier_values):
                    raise RuntimeError("monoid stream advanced beyond shared table")
                heappush(
                    self.monoid_heap,
                    (
                        prime * self.multiplier_values[next_index],
                        prime,
                        next_index,
                    ),
                )
            return

    def _ensure_multiplier_index(self, index: int) -> None:
        if index < 0:
            raise ValueError("multiplier index must be nonnegative")
        while index >= len(self.multiplier_values):
            self._append_next_multiplier()

    def _find_multiplier_successor(self, stream_prime: int, index: int) -> int:
        self._ensure_multiplier_index(index)
        parents = self.multiplier_successors.setdefault(stream_prime, {})
        current = index
        path: list[int] = []
        while current in parents:
            path.append(current)
            current = parents[current]
            self._ensure_multiplier_index(current)
        for item in path:
            parents[item] = current
        return current

    def _delete_multiplier_index(self, stream_prime: int, index: int) -> bool:
        surviving = self._find_multiplier_successor(stream_prime, index)
        if surviving != index:
            return False
        parents = self.multiplier_successors.setdefault(stream_prime, {})
        parents[index] = self._find_multiplier_successor(stream_prime, index + 1)
        return True

    def _next_unused_multiplier_index(self, stream_prime: int, index: int) -> int:
        parents = self.multiplier_successors.setdefault(stream_prime, {})
        index = self._find_multiplier_successor(stream_prime, index)
        while True:
            multiplier = self.multiplier_values[index]
            if stream_prime * multiplier not in self.used:
                return index
            successor = self._find_multiplier_successor(stream_prime, index + 1)
            parents[index] = successor
            index = successor

    def _next_stream_index(
        self,
        stream_prime: int,
        lower_index: int,
        forbidden_radical: int,
    ) -> int:
        index = max(0, lower_index)
        while True:
            index = self._next_unused_multiplier_index(stream_prime, index)
            multiplier = self.multiplier_values[index]
            if gcd(multiplier, forbidden_radical) == 1:
                return index
            index += 1

    @staticmethod
    def _multiplier_introduces_new_prime(
        multiplier: int,
        previous_support: frozenset[int],
    ) -> bool:
        remainder = multiplier
        for prime in previous_support:
            while remainder % prime == 0:
                remainder //= prime
            if remainder == 1:
                return False
        return remainder > 1

    def _retire_used_value(self, value: int) -> None:
        for stream_prime in prime_support(value):
            multiplier = value // stream_prime
            if multiplier > self.multiplier_values[-1]:
                continue
            index = bisect_left(self.multiplier_values, multiplier)
            if (
                index < len(self.multiplier_values)
                and self.multiplier_values[index] == multiplier
            ):
                self._delete_multiplier_index(stream_prime, index)

    def _next_candidate(self) -> int:
        previous = self.terms[-1]
        two_back = self.terms[-2]
        previous_support = prime_support(previous)
        two_back_support = prime_support(two_back)
        shared_primes = tuple(sorted(previous_support - two_back_support))
        if not shared_primes:
            raise RuntimeError(
                "sparse prime-coordinate EW state has no predecessor prime "
                "disjoint from the two-back term"
            )

        heap: list[tuple[int, int, int, int]] = []
        earlier_shared_product = 1
        two_back_radical = prod(two_back_support)

        for stream_prime in shared_primes:
            forbidden_radical = two_back_radical * earlier_shared_product
            index = self._next_stream_index(stream_prime, 0, forbidden_radical)
            multiplier = self.multiplier_values[index]
            heappush(
                heap,
                (
                    stream_prime * multiplier,
                    stream_prime,
                    index,
                    forbidden_radical,
                ),
            )
            earlier_shared_product *= stream_prime

        while heap:
            candidate, stream_prime, index, forbidden_radical = heappop(heap)
            multiplier = self.multiplier_values[index]

            if self._multiplier_introduces_new_prime(multiplier, previous_support):
                return candidate

            index = self._next_stream_index(
                stream_prime,
                index + 1,
                forbidden_radical,
            )
            multiplier = self.multiplier_values[index]
            heappush(
                heap,
                (
                    stream_prime * multiplier,
                    stream_prime,
                    index,
                    forbidden_radical,
                ),
            )

        raise RuntimeError("sparse prime-coordinate candidate heap unexpectedly exhausted")

    def extend_to(self, count: int) -> None:
        if count < 0:
            raise ValueError("count must be nonnegative")
        if count <= len(self.terms):
            return

        while len(self.terms) < count:
            candidate = self._next_candidate()
            self.terms.append(candidate)
            self.used.add(candidate)
            self._retire_used_value(candidate)


def make_sparse_prime_index_only_enots_wolley_definition(
    *,
    id: str,
    family: PrimeIndexFamily,
    name: str,
    aliases: tuple[str, ...] = (),
    description: str,
) -> SequenceDefinition[int]:
    """Build one registered sparse-prime-index-only EW sequence."""

    _validate_family(family)
    return SequenceDefinition[int](
        id=id,
        oeis=None,
        name=name,
        aliases=aliases,
        generator_factory=partial(SparsePrimeIndexOnlyEnotsWolleyGenerator, family=family),
        generator_version=1,
        definition_version=1,
        offset=1,
        object_space=PositiveIntegers(),
        projections={"prime-exponents": prime_exponent_projection()},
        description=description,
    )


SQUARE_INDEX_PRIME_ONLY_ENOTS_WOLLEY = make_sparse_prime_index_only_enots_wolley_definition(
    id="X000012",
    family="square",
    name="Square-index-prime-only Enots--Wolley",
    aliases=(
        "square-index-prime-only-ew",
        "prime-coordinate-square-ew",
    ),
    description=(
        "Lexicographically earliest sequence starting 1, 2 and obeying the "
        "Enots--Wolley rule after retaining only prime coordinates "
        "p_1, p_4, p_9, p_16, ... ."
    ),
)

POWER_OF_TWO_INDEX_PRIME_ONLY_ENOTS_WOLLEY = (
    make_sparse_prime_index_only_enots_wolley_definition(
        id="X000013",
        family="power_of_two",
        name="Power-of-two-index-prime-only Enots--Wolley",
        aliases=(
            "power-of-two-index-prime-only-ew",
            "prime-coordinate-power-of-two-ew",
        ),
        description=(
            "Lexicographically earliest sequence starting 1, 2 and obeying the "
            "Enots--Wolley rule after retaining only prime coordinates "
            "p_1, p_2, p_4, p_8, p_16, ... ."
        ),
    )
)

SELF_POWER_INDEX_PRIME_ONLY_ENOTS_WOLLEY = make_sparse_prime_index_only_enots_wolley_definition(
    id="X000014",
    family="self_power",
    name="Self-power-index-prime-only Enots--Wolley",
    aliases=(
        "self-power-index-prime-only-ew",
        "prime-coordinate-self-power-ew",
    ),
    description=(
        "Lexicographically earliest sequence starting 1, 2 and obeying the "
        "Enots--Wolley rule after retaining only prime coordinates "
        "p_1, p_4, p_27, p_256, ... ."
    ),
)

SPARSE_PRIME_INDEX_ONLY_ENOTS_WOLLEY_DEFINITIONS = (
    SQUARE_INDEX_PRIME_ONLY_ENOTS_WOLLEY,
    POWER_OF_TWO_INDEX_PRIME_ONLY_ENOTS_WOLLEY,
    SELF_POWER_INDEX_PRIME_ONLY_ENOTS_WOLLEY,
)
