"""Enots--Wolley on sparse prime-index coordinate systems.

The allowed prime coordinates are selected by their one-based prime index.
Three registered families are provided:

- square indices: ``p_1, p_4, p_9, p_16, ...``;
- powers of two: ``p_1, p_2, p_4, p_8, ...``;
- self powers: ``p_1, p_4, p_27, p_256, ...``.

This is intentionally a simple first implementation.  It uses the same shared
retained-monoid multiplier table idea as the every-k-th-prime-only family, but
with a generic prime-index predicate instead of the stride-specific test.
"""

from __future__ import annotations

from bisect import bisect_left
from dataclasses import dataclass, field
from functools import partial
from heapq import heappop, heappush
from math import gcd, isqrt, prod
from typing import Literal

from ..core import SequenceDefinition
from ..object_space import PositiveIntegers
from ..projections import prime_exponent_projection, primes_through
from .enots_wolley import is_candidate, prime_support
from .every_kth_prime_enots_wolley import prime_index

PrimeIndexFamily = Literal["square", "power_of_two", "self_power"]

_VALID_FAMILIES: frozenset[str] = frozenset(
    {"square", "power_of_two", "self_power"}
)


def _validate_family(family: str) -> None:
    if family not in _VALID_FAMILIES:
        allowed = ", ".join(sorted(_VALID_FAMILIES))
        raise ValueError(f"unknown prime-index family {family!r}; expected one of {allowed}")


def is_retained_prime_index(index: int, family: PrimeIndexFamily) -> bool:
    """Return whether one-based prime index ``index`` belongs to ``family``."""

    _validate_family(family)
    if type(index) is not int:
        raise TypeError("prime index must be an integer")
    if index < 1:
        return False

    if family == "square":
        root = isqrt(index)
        return root * root == index

    if family == "power_of_two":
        return index & (index - 1) == 0

    # self_power: 1^1, 2^2, 3^3, ...
    base = 1
    while True:
        value = base**base
        if value >= index:
            return value == index
        base += 1


def is_retained_prime(value: int, family: PrimeIndexFamily) -> bool:
    """Return whether prime ``value`` is retained by the selected index family."""

    index = prime_index(value)
    return index is not None and is_retained_prime_index(index, family)


@dataclass(frozen=True, slots=True)
class SparsePrimeIndexOnlyPolicy:
    """Allow exactly integers supported on one sparse prime-index family."""

    family: PrimeIndexFamily

    def __post_init__(self) -> None:
        _validate_family(self.family)

    def allows(self, value: int) -> bool:
        if value < 2:
            return False
        support = prime_support(value)
        return bool(support) and all(
            is_retained_prime(prime, self.family) for prime in support
        )


@dataclass
class ReferenceSparsePrimeIndexOnlyEnotsWolleyGenerator:
    """Very slow direct integer scanner used as a correctness oracle."""

    family: PrimeIndexFamily = "square"
    policy: SparsePrimeIndexOnlyPolicy = field(init=False)
    terms: list[int] = field(init=False)
    used: set[int] = field(init=False)

    def __post_init__(self) -> None:
        _validate_family(self.family)
        self.policy = SparsePrimeIndexOnlyPolicy(self.family)
        self.terms = [1, 2]
        self.used = {1, 2}

    def _next_candidate(self) -> int:
        previous = self.terms[-1]
        two_back = self.terms[-2]
        candidate = 2
        while True:
            if (
                candidate not in self.used
                and self.policy.allows(candidate)
                and is_candidate(candidate, previous, two_back)
            ):
                return candidate
            candidate += 1

    def extend_to(self, count: int) -> None:
        if count < 0:
            raise ValueError("count must be nonnegative")
        if count <= len(self.terms):
            return
        while len(self.terms) < count:
            candidate = self._next_candidate()
            self.terms.append(candidate)
            self.used.add(candidate)


@dataclass
class SparsePrimeIndexOnlyEnotsWolleyGenerator:
    """Simple retained-monoid EW generator for sparse prime-index families."""

    family: PrimeIndexFamily = "square"
    policy: SparsePrimeIndexOnlyPolicy = field(init=False)
    terms: list[int] = field(init=False)
    used: set[int] = field(init=False)

    # Increasing values in the multiplicative monoid generated by retained primes.
    multiplier_values: list[int] = field(default_factory=lambda: [1], repr=False)
    multiplier_limit: int = 1

    # Per stream-prime successor-with-delete tables over multiplier_values.
    multiplier_successors: dict[int, dict[int, int]] = field(
        default_factory=dict,
        repr=False,
    )

    def __post_init__(self) -> None:
        _validate_family(self.family)
        self.policy = SparsePrimeIndexOnlyPolicy(self.family)
        self.terms = [1, 2]
        self.used = {1, 2}

    def _extend_multiplier_table(self, required_value: int) -> None:
        """Extend the retained-prime multiplicative monoid through a value."""

        if required_value <= self.multiplier_limit:
            return

        while self.multiplier_limit < required_value:
            lower = self.multiplier_limit + 1
            upper = max(required_value, 64, 2 * self.multiplier_limit)
            flags = bytearray(b"\x01") * (upper - lower + 1)

            for index, prime in enumerate(primes_through(upper), start=1):
                if is_retained_prime_index(index, self.family):
                    continue
                first = ((lower + prime - 1) // prime) * prime
                if first > upper:
                    continue
                offset = first - lower
                count = (upper - first) // prime + 1
                flags[offset::prime] = b"\x00" * count

            self.multiplier_values.extend(
                lower + offset for offset, allowed in enumerate(flags) if allowed
            )
            self.multiplier_limit = upper

    def _ensure_multiplier_index(self, index: int) -> None:
        if index < 0:
            raise ValueError("multiplier index must be nonnegative")
        while index >= len(self.multiplier_values):
            self._extend_multiplier_table(max(64, 2 * self.multiplier_limit))

    def _find_multiplier_successor(self, stream_prime: int, index: int) -> int:
        self._ensure_multiplier_index(index)
        parents = self.multiplier_successors.setdefault(stream_prime, {})
        current = index
        path: list[int] = []
        while current in parents:
            path.append(current)
            current = parents[current]
            self._ensure_multiplier_index(current)
        for item in path:
            parents[item] = current
        return current

    def _delete_multiplier_index(self, stream_prime: int, index: int) -> bool:
        surviving = self._find_multiplier_successor(stream_prime, index)
        if surviving != index:
            return False
        parents = self.multiplier_successors.setdefault(stream_prime, {})
        parents[index] = self._find_multiplier_successor(stream_prime, index + 1)
        return True

    def _next_unused_multiplier_index(self, stream_prime: int, index: int) -> int:
        parents = self.multiplier_successors.setdefault(stream_prime, {})
        index = self._find_multiplier_successor(stream_prime, index)
        while True:
            multiplier = self.multiplier_values[index]
            if stream_prime * multiplier not in self.used:
                return index
            successor = self._find_multiplier_successor(stream_prime, index + 1)
            parents[index] = successor
            index = successor

    def _next_stream_index(
        self,
        stream_prime: int,
        lower_index: int,
        forbidden_radical: int,
    ) -> int:
        index = max(0, lower_index)
        while True:
            index = self._next_unused_multiplier_index(stream_prime, index)
            multiplier = self.multiplier_values[index]
            if gcd(multiplier, forbidden_radical) == 1:
                return index
            index += 1

    @staticmethod
    def _multiplier_introduces_new_prime(
        multiplier: int,
        previous_support: frozenset[int],
    ) -> bool:
        remainder = multiplier
        for prime in previous_support:
            while remainder % prime == 0:
                remainder //= prime
            if remainder == 1:
                return False
        return remainder > 1

    def _retire_used_value(self, value: int) -> None:
        for stream_prime in prime_support(value):
            multiplier = value // stream_prime
            if multiplier > self.multiplier_limit:
                continue
            index = bisect_left(self.multiplier_values, multiplier)
            if (
                index < len(self.multiplier_values)
                and self.multiplier_values[index] == multiplier
            ):
                self._delete_multiplier_index(stream_prime, index)

    def _next_candidate(self) -> int:
        previous = self.terms[-1]
        two_back = self.terms[-2]
        previous_support = prime_support(previous)
        two_back_support = prime_support(two_back)
        shared_primes = tuple(sorted(previous_support - two_back_support))
        if not shared_primes:
            raise RuntimeError(
                "sparse prime-coordinate EW state has no predecessor prime "
                "disjoint from the two-back term"
            )

        heap: list[tuple[int, int, int, int]] = []
        earlier_shared_product = 1
        two_back_radical = prod(two_back_support)

        for stream_prime in shared_primes:
            forbidden_radical = two_back_radical * earlier_shared_product
            index = self._next_stream_index(stream_prime, 0, forbidden_radical)
            multiplier = self.multiplier_values[index]
            heappush(
                heap,
                (
                    stream_prime * multiplier,
                    stream_prime,
                    index,
                    forbidden_radical,
                ),
            )
            earlier_shared_product *= stream_prime

        while heap:
            candidate, stream_prime, index, forbidden_radical = heappop(heap)
            multiplier = self.multiplier_values[index]

            if self._multiplier_introduces_new_prime(multiplier, previous_support):
                return candidate

            index = self._next_stream_index(
                stream_prime,
                index + 1,
                forbidden_radical,
            )
            multiplier = self.multiplier_values[index]
            heappush(
                heap,
                (
                    stream_prime * multiplier,
                    stream_prime,
                    index,
                    forbidden_radical,
                ),
            )

        raise RuntimeError("sparse prime-coordinate candidate heap unexpectedly exhausted")

    def extend_to(self, count: int) -> None:
        if count < 0:
            raise ValueError("count must be nonnegative")
        if count <= len(self.terms):
            return

        while len(self.terms) < count:
            candidate = self._next_candidate()
            self.terms.append(candidate)
            self.used.add(candidate)
            self._retire_used_value(candidate)


def make_sparse_prime_index_only_enots_wolley_definition(
    *,
    id: str,
    family: PrimeIndexFamily,
    name: str,
    aliases: tuple[str, ...] = (),
    description: str,
) -> SequenceDefinition[int]:
    """Build one registered sparse-prime-index-only EW sequence."""

    _validate_family(family)
    return SequenceDefinition[int](
        id=id,
        oeis=None,
        name=name,
        aliases=aliases,
        generator_factory=partial(SparsePrimeIndexOnlyEnotsWolleyGenerator, family=family),
        generator_version=1,
        definition_version=1,
        offset=1,
        object_space=PositiveIntegers(),
        projections={"prime-exponents": prime_exponent_projection()},
        description=description,
    )


SQUARE_INDEX_PRIME_ONLY_ENOTS_WOLLEY = make_sparse_prime_index_only_enots_wolley_definition(
    id="X000012",
    family="square",
    name="Square-index-prime-only Enots--Wolley",
    aliases=(
        "square-index-prime-only-ew",
        "prime-coordinate-square-ew",
    ),
    description=(
        "Lexicographically earliest sequence starting 1, 2 and obeying the "
        "Enots--Wolley rule after retaining only prime coordinates "
        "p_1, p_4, p_9, p_16, ... ."
    ),
)

POWER_OF_TWO_INDEX_PRIME_ONLY_ENOTS_WOLLEY = (
    make_sparse_prime_index_only_enots_wolley_definition(
        id="X000013",
        family="power_of_two",
        name="Power-of-two-index-prime-only Enots--Wolley",
        aliases=(
            "power-of-two-index-prime-only-ew",
            "prime-coordinate-power-of-two-ew",
        ),
        description=(
            "Lexicographically earliest sequence starting 1, 2 and obeying the "
            "Enots--Wolley rule after retaining only prime coordinates "
            "p_1, p_2, p_4, p_8, p_16, ... ."
        ),
    )
)

SELF_POWER_INDEX_PRIME_ONLY_ENOTS_WOLLEY = make_sparse_prime_index_only_enots_wolley_definition(
    id="X000014",
    family="self_power",
    name="Self-power-index-prime-only Enots--Wolley",
    aliases=(
        "self-power-index-prime-only-ew",
        "prime-coordinate-self-power-ew",
    ),
    description=(
        "Lexicographically earliest sequence starting 1, 2 and obeying the "
        "Enots--Wolley rule after retaining only prime coordinates "
        "p_1, p_4, p_27, p_256, ... ."
    ),
)

SPARSE_PRIME_INDEX_ONLY_ENOTS_WOLLEY_DEFINITIONS = (
    SQUARE_INDEX_PRIME_ONLY_ENOTS_WOLLEY,
    POWER_OF_TWO_INDEX_PRIME_ONLY_ENOTS_WOLLEY,
    SELF_POWER_INDEX_PRIME_ONLY_ENOTS_WOLLEY,
)
